# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'corona.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(796, 435)
        Form.setMaximumSize(QtCore.QSize(796, 435))
        Form.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.TWConductor = QtGui.QTableWidget(Form)
        self.TWConductor.setGeometry(QtCore.QRect(465, 10, 321, 192))
        self.TWConductor.setMaximumSize(QtCore.QSize(421, 192))
        self.TWConductor.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.TWConductor.setRowCount(1)
        self.TWConductor.setColumnCount(2)
        self.TWConductor.setObjectName(_fromUtf8("TWConductor"))
        item = QtGui.QTableWidgetItem()
        self.TWConductor.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.TWConductor.setHorizontalHeaderItem(1, item)
        self.TWConductor.horizontalHeader().setVisible(True)
        self.TWConductor.horizontalHeader().setCascadingSectionResizes(False)
        self.TWConductor.horizontalHeader().setDefaultSectionSize(150)
        self.TWConductor.horizontalHeader().setMinimumSectionSize(33)
        self.TWConductor.verticalHeader().setDefaultSectionSize(20)
        self.SBconductor = QtGui.QSpinBox(Form)
        self.SBconductor.setGeometry(QtCore.QRect(420, 10, 42, 22))
        self.SBconductor.setMinimum(1)
        self.SBconductor.setMaximum(30)
        self.SBconductor.setObjectName(_fromUtf8("SBconductor"))
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(350, 5, 81, 51))
        self.label.setObjectName(_fromUtf8("label"))
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(14, 11, 286, 251))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.leU1 = QtGui.QLineEdit(self.layoutWidget)
        self.leU1.setObjectName(_fromUtf8("leU1"))
        self.gridLayout.addWidget(self.leU1, 3, 1, 1, 1)
        self.leTemp = QtGui.QLineEdit(self.layoutWidget)
        self.leTemp.setObjectName(_fromUtf8("leTemp"))
        self.gridLayout.addWidget(self.leTemp, 2, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.leU2 = QtGui.QLineEdit(self.layoutWidget)
        self.leU2.setObjectName(_fromUtf8("leU2"))
        self.gridLayout.addWidget(self.leU2, 4, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.leFr = QtGui.QLineEdit(self.layoutWidget)
        self.leFr.setObjectName(_fromUtf8("leFr"))
        self.gridLayout.addWidget(self.leFr, 5, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.leVn = QtGui.QLineEdit(self.layoutWidget)
        self.leVn.setObjectName(_fromUtf8("leVn"))
        self.gridLayout.addWidget(self.leVn, 0, 1, 1, 1)
        self.lePr = QtGui.QLineEdit(self.layoutWidget)
        self.lePr.setObjectName(_fromUtf8("lePr"))
        self.gridLayout.addWidget(self.lePr, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 7, 0, 1, 1)
        self.leRe = QtGui.QLineEdit(self.layoutWidget)
        self.leRe.setText(_fromUtf8(""))
        self.leRe.setObjectName(_fromUtf8("leRe"))
        self.gridLayout.addWidget(self.leRe, 7, 1, 1, 1)
        self.leDiametro = QtGui.QLineEdit(self.layoutWidget)
        self.leDiametro.setText(_fromUtf8(""))
        self.leDiametro.setObjectName(_fromUtf8("leDiametro"))
        self.gridLayout.addWidget(self.leDiametro, 6, 1, 1, 1)
        self.TWSubconductor = QtGui.QTableWidget(Form)
        self.TWSubconductor.setGeometry(QtCore.QRect(465, 220, 321, 192))
        self.TWSubconductor.setMaximumSize(QtCore.QSize(421, 192))
        self.TWSubconductor.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.TWSubconductor.setRowCount(1)
        self.TWSubconductor.setColumnCount(2)
        self.TWSubconductor.setObjectName(_fromUtf8("TWSubconductor"))
        item = QtGui.QTableWidgetItem()
        self.TWSubconductor.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.TWSubconductor.setHorizontalHeaderItem(1, item)
        self.TWSubconductor.horizontalHeader().setVisible(True)
        self.TWSubconductor.horizontalHeader().setCascadingSectionResizes(False)
        self.TWSubconductor.horizontalHeader().setDefaultSectionSize(150)
        self.TWSubconductor.verticalHeader().setDefaultSectionSize(20)
        self.label_12 = QtGui.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(350, 215, 81, 51))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.SBsubconductor = QtGui.QSpinBox(Form)
        self.SBsubconductor.setGeometry(QtCore.QRect(420, 220, 42, 22))
        self.SBsubconductor.setMinimum(1)
        self.SBsubconductor.setMaximum(10)
        self.SBsubconductor.setObjectName(_fromUtf8("SBsubconductor"))
        self.PBShowCond = QtGui.QPushButton(Form)
        self.PBShowCond.setGeometry(QtCore.QRect(350, 390, 75, 23))
        self.PBShowCond.setObjectName(_fromUtf8("PBShowCond"))
        self.checkBox = QtGui.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(350, 50, 70, 17))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkBox_2 = QtGui.QCheckBox(Form)
        self.checkBox_2.setGeometry(QtCore.QRect(350, 270, 70, 17))
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.clcTW1 = QtGui.QPushButton(Form)
        self.clcTW1.setGeometry(QtCore.QRect(350, 70, 75, 23))
        self.clcTW1.setObjectName(_fromUtf8("clcTW1"))
        self.clcTW2 = QtGui.QPushButton(Form)
        self.clcTW2.setGeometry(QtCore.QRect(350, 290, 75, 23))
        self.clcTW2.setObjectName(_fromUtf8("clcTW2"))

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.clcTW1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.TWConductor.clearContents)
        QtCore.QObject.connect(self.clcTW2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.TWSubconductor.clearContents)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.leVn, self.lePr)
        Form.setTabOrder(self.lePr, self.leTemp)
        Form.setTabOrder(self.leTemp, self.leU1)
        Form.setTabOrder(self.leU1, self.leU2)
        Form.setTabOrder(self.leU2, self.leFr)
        Form.setTabOrder(self.leFr, self.leDiametro)
        Form.setTabOrder(self.leDiametro, self.leRe)
        Form.setTabOrder(self.leRe, self.SBconductor)
        Form.setTabOrder(self.SBconductor, self.TWConductor)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        item = self.TWConductor.horizontalHeaderItem(0)
        item.setText(_translate("Form", "X", None))
        item = self.TWConductor.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Y", None))
        self.label.setText(_translate("Form", "<html><head/><body><p>Número de </p><p>condcutores</p></body></html>", None))
        self.label_2.setText(_translate("Form", "Tensión nominal [kV]: ", None))
        self.label_5.setText(_translate("Form", "Temperatura [°C]:", None))
        self.leU1.setText(_translate("Form", "0,85", None))
        self.label_7.setText(_translate("Form", "Factor de clima", None))
        self.leU2.setText(_translate("Form", "1", None))
        self.label_8.setText(_translate("Form", "Frecuencia [Hz]:", None))
        self.leFr.setText(_translate("Form", "60", None))
        self.label_9.setText(_translate("Form", "Diametro del conductor [mm]:", None))
        self.label_6.setText(_translate("Form", "Factor de rugosidad", None))
        self.label_4.setText(_translate("Form", "Presión [kPa]:", None))
        self.label_10.setText(_translate("Form", "<html><head/><body><p>Resistencia del conductor [Ω]:</p></body></html>", None))
        item = self.TWSubconductor.horizontalHeaderItem(0)
        item.setText(_translate("Form", "X", None))
        item = self.TWSubconductor.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Y", None))
        self.label_12.setText(_translate("Form", "<html><head/><body><p>Número de </p><p>subcondcutores</p></body></html>", None))
        self.PBShowCond.setText(_translate("Form", "Visualizar", None))
        self.checkBox.setText(_translate("Form", "Dibujar", None))
        self.checkBox_2.setText(_translate("Form", "Dibujar", None))
        self.clcTW1.setText(_translate("Form", "limpiar tabla", None))
        self.clcTW2.setText(_translate("Form", "limpiar tabla", None))

